# Environment variables:
# - DOCKER_REGISTRY_SERVER
# - DOMAIN
# - GITPOD_VERSION
# - MYSQL_GITPOD_PASSWORD
# - MYSQL_INSTANCE_NAME
# - LOCATION
# - MINIO_ACCESS_KEY
# - MINIO_SECRET_KEY

hostname: $DOMAIN

imagePrefix: gcr.io/gitpod-io/self-hosted/
version: $GITPOD_VERSION

installation:
  region: $LOCATION

certificatesSecret:
  secretName: proxy-config-certificates

installPodSecurityPolicies: true

resources:
  default:
    cpu: 1m
    memory: 256Mi

workspaceSizing:
  requests:
    cpu: 1m
    memory: 1.75Gi
    storage: ""
  limits:
    cpu: "6"
    memory: 12Gi
  dynamic:
    cpu:
      buckets:
        - budget: 144000
          limit: 600
        - budget: 144000
          limit: 400
        - budget: 54000
          limit: 200
      controlPeriod: 15m
      samplingPeriod: 10s

# default affinity for gitpod components
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: gitpod.io/workload_services
              operator: In
              values:
                - "true"

db:
  enabled: true
  autoMigrate: true

# @todo disable local mysql
mysql:
  enabled: true

# Azure blob storage isn't S3 compatible
minio:
  enabled: true
  accessKey: $MINIO_ACCESS_KEY
  secretKey: $MINIO_SECRET_KEY

docker-registry:
  enabled: false

rabbitmq:
  readinessProbe:
    enabled: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gitpod.io/workload_services
                operator: In
                values:
                  - "true"
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: rabbitmq
            topologyKey: kubernetes.io/hostname
          weight: 1
  replicas: 2
  auth:
    username: "gitpod"
    password: "4B6e7m2QjpCgrz9DQT"

defaults:
  dnsPolicy: ClusterFirst
  restartPolicy: Always

tracing:
  endoint: http://jaeger-collector:14268/api/traces
  samplerType: const
  samplerParam: "1"

# TODO: empty array means no login.
authProviders: []

workspaceScheduler: default-scheduler

components:
  agentSmith:
    disabled: true

  db:
    gcloudSqlProxy:
      enabled: false

  dbMigrations:
    enabled: true

  imageBuilder:
    registryCerts: []
    registry:
      name: $DOCKER_REGISTRY_SERVER
      secretName: image-builder-registry-secret
      path: secrets/registry-auth.json

  registryFacade:
    hostname: $DOMAIN
    daemonSet: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: gitpod.io/workload_workspaces
                  operator: In
                  values:
                    - "true"
  server:
    defaultFeatureFlags: []
    imageName: server
    github:
      app: {}
    enableLocalApp: false
    enableOAuthServer: true
    blockNewUsers: false
    blockNewUsersPasslist: []
    makeNewUsersAdmin: false
    sessionMaxAgeMs: "28800000" # 8 hours
    defaultBaseImageRegistryWhitelist:
      - "https://index.docker.io/v1/"
    incrementalPrebuilds:
      commitHistory: 100
      repositoryPasslist: []
    wsman: []
    serverContainer:
      env:
        - name: ENABLE_PAYMENT
          value: "false"

  workspace:
    pullSecret:
      secretName: image-builder-registry-secret
    affinity:
      prebuild: "gitpod.io/workload_workspaces"
      probe: "gitpod.io/workload_workspaces"
      default: "gitpod.io/workload_workspaces"
    templates:
      default:
        spec:
          #dnsConfig:
          #  nameservers:
          #    - 1.1.1.1
          #    - 8.8.8.8
          #dnsPolicy: None # do NOT query against K8s DNS (https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)
          env:
            - name: THEIA_PREVENT_METADATA_ACCESS
              value: true
      regular:
        spec:
          containers:
            - name: workspace
              env:
                - name: THEIA_RATELIMIT_LOG
                  value: "50"
      prebuild:
        spec:
          containers:
            - name: workspace
              # Intended to reduce the density for prebuilds
              resources:
                limits:
                  cpu: "5"
                  memory: 12Gi
                requests:
                  cpu: 1m
                  ephemeral-storage: 5Gi
                  memory: 4608Mi # = 2 * 2304Mi

  proxy:
    replicas: 2
    ports:
      http:
        expose: true
        containerPort: 80
      https:
        expose: true
        containerPort: 443
    certManager:
      issuerName: azure-issuer
      issuerKind: ClusterIssuer
    serviceExternalTrafficPolicy: Local
    serviceType: LoadBalancer
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: $DOMAIN,*.$DOMAIN,*.ws.$DOMAIN
      cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "gitpod-proxy-http"},"443": {"name": "gitpod-proxy-https"}}}'

  wsManagerBridge:
    defaultConfig: true

  wsDaemon:
    containerRuntime:
      nodeRoots:
        - /run/containerd/io.containerd.runtime.v1.linux/k8s.io

  contentService: {}

  wsScheduler:
    name: ws-scheduler
    disabled: true
    scalerDisabled: true

  wsProxy:
    name: ws-proxy
    disabled: false
    replicas: 2
    hostHeader: x-wsproxy-host
    ports:
      metrics:
        expose: false
        containerPort: 60095
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: gitpod.io/workload_services
                  operator: In
                  values:
                    - "true"
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - ws-proxy
              topologyKey: kubernetes.io/hostname
            weight: 100

  wsManager: {}

# configure default log level
log:
  level: info

cert-manager:
  enabled: true
  install: false
